### ISSUE TITLE
Official repository with Composer support

### ISSUE THREAD

**Issue by mundschenk-at** [debach/php-typography#1]
I just wanted to let you know that I've taken over maintenance of wp-Typography/PHP-Typography from Jeff and there is a new official repository for [PHP-Typography](https://github.com/mundschenk-at/php-typography) (with Composer support). Any pull requests and issue reports would be welcome.

**Comment by debach** [comment]
I’m happy that the great typography library is maintained again. Thanks a lot for letting me know and apologies for the very late reply. I will deprecate this repository and redirect people to you.
